# Generated by Django 5.2.7 on 2025-11-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="test_field",
            field=models.TextField(max_length=125, null=True),
        ),
    ]
